### ISSUE TITLE
Error en CSS

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-local_notificationsagent#91]
La regla CSS 
```CSS
body.path-local-notificationsagent .card {
    height: 500px
}
```
Provoca cambios en otros contendores de cards.
![image](https://github.com/UNIMOODLE/moodle-local_notificationsagent/assets/1656180/aabb6f11-9e12-49bd-915d-3c4fdbeb055a)

Debe ser (sin espacio).

```CSS
body.path-local-notificationsagent.card {
    height: 500px
}
```

Revisad el resto de CSS con theme Boost y Classic al menos.
